---
driver:
  name: hyperv
  parent_vhd_folder: c:\kitchen\2012r2-master-sp
  parent_vhd_name: kitchen-master-2012r2.vhdx
  vm_switch: External-WiFi
  memory_startup_bytes: 2GB
  vm_generation: 2
  processor_count: 2

transport:
  password: Password12345
  username: kitchen
  name: winrm

verifier:
  name: inspec

provisioner:
  name: chef_zero
  retry_on_exit_code:
    - 35
  max_retries: 2
  wait_for_retry: 300

platforms:
  - name: windows-2012r2

suites:
  - name: registry
    run_list:
      - recipe[braves::registry]
    attributes:
    verifier:
      inspec_tests:
        - test/smoke/registry
